---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "default"
  labels:
    app: "postgres"
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "postgres"
  namespace: "default"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:alpine"
        env:
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
# Horizontal autoscaling group for PGSQL
#---
#apiVersion: "autoscaling/v1"
#kind: "HorizontalPodAutoscaler"
#metadata:
#  name: "postgres-hpa"
#  namespace: "default"
#  labels:
#    app: "postgres"
#spec:
#  scaleTargetRef:
#    kind: "Deployment"
#    name: "postgres"
#    apiVersion: "apps/v1beta1"
#  minReplicas: 1
#  maxReplicas: 5
#  targetCPUUtilizationPercentage: 80
#
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres"
  namespace: "default"
  labels:
    app: "postgres"
spec:
  ports:
  - protocol: "TCP"
    port: 5432
  selector:
    app: "postgres"
  type: "ClusterIP"

# example app deploy
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "example-elixir-config"
  namespace: "default"
  labels:
    app: "example-elixir"
data:
  DATABASE_HOST: "postgres"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "example-elixir"
  namespace: "default"
  labels:
    app: "example-elixir"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "example-elixir"
  template:
    metadata:
      labels:
        app: "example-elixir"
    spec:
      containers:
      - name: "example-phoenix-app"
        image: "firestarter/example-phoenix-app:latest"
        env:
        - name: "DATABASE_HOST"
          valueFrom:
            configMapKeyRef:
              key: "DATABASE_HOST"
              name: "example-elixir-config"
#---
#apiVersion: "autoscaling/v1"
#kind: "HorizontalPodAutoscaler"
#metadata:
#  name: "example-elixir-hpa"
#  namespace: "default"
#  labels:
#    app: "example-elixir"
#spec:
#  scaleTargetRef:
#    kind: "Deployment"
#    name: "example-elixir"
#    apiVersion: "apps/v1beta1"
#  minReplicas: 1
#  maxReplicas: 5
#  targetCPUUtilizationPercentage: 80

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "example-elixir-service"
  namespace: "default"
  labels:
    app: "example-elixir"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "example-elixir"
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-elixir-ingress
spec:
  rules:
  - host: talam-atman.auroville.org.in
    http:
      paths:
      - backend:
          serviceName: example-elixir-service
          servicePort: 80
