sudo: required

# safelist
branches:
  only:
  - master
  - dev

language: elixir
elixir: '1.6'
otp_release: '20.0'
services:
- docker
env:
  global:
  - IMAGE_NAME=firestarter/example-phoenix-app
  - REGISTRY_USER=firestarter
  # REGISTRY_PASS=...
  - secure: teccPk538YYCxh4XyQFc7txDwWtIsYcOkSlOFCmjcbYauqxW6YrpZbwwPOhIhFXvXjD5odJGS8/3pCMPhAPes+Z2LsS6g1F+SCiG/EJWzJHYjos79EW7i1Sxzw86SdGb4sJRbzyyIWQBmLEH+HSqti4KVbbcWuQSNefmZ8W9MgNmt4obP/BwBhLvXrtu+IaQ4245KWIGJt+BvvB9GV/X/Q6cNv2LouxUtNhv7+Hr18JrACDaGfZzwqyPU5eiVb0uC4w7I86SwpQZcmKudk1bZlgs41xWhHQJzLpw9u/0XLt4bgIQdyOvXCruNAP/+D+B7I1KRaYXjZw9mwUxnsfhwwpm5NUVBwct+gfq1eQSefzbrY2pLCESv65Qf6M/HzkzOt9WqXrXyBMEWZc8KJLrQ0i6ek8nvGsfj7wljNaBe6amL96YulDt/y4te58lUN5NflILXBLhKineqYnxzm/8lscDXHH8Ce5k/7gY4jErFwT0WU1DPyC8QBk67NjyXDVT0OBl7dQapMe3h8xlpxBUD3s1ipn3gcTmJSAXO5MtZzOqJkZI5a3mAum/+7g17YFo0w4nILoN/Kv838yNZeSmzo0OIjeV/+LnPBJkF9EHijvUA6EuQjKVZ52XUbzN7YPmE83fm7++2tPZfwJ+5KJndIKz4J0Y+Sj3RVLJmZht64o=

install: "./install-dependencies.sh"
before_script:
- docker pull "$IMAGE_NAME" || true

script:
- "./build-script.sh"
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- VERSION=$TRAVIS_BRANCH`date '+%Y-%m-%d.%H-%M-%S'`
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"
deploy:
  skip_cleanup: true
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${VERSION}"
  on: 
    branch: master

after_deploy:
- kubectl config set-cluster talam-atman --insecure-skip-tls-verify=true --server=$KUBE_BOT_SERVER
- kubectl config set-credentials $KUBE_BOT_USER --token $KUBE_BOT_TOKEN
- kubectl config set-context default-talam-atman --user $KUBE_BOT_USER --namespace default --cluster talam-atman
- kubectl config use-context default-talam-atman
- kubectl version
- echo $VERSION
- if [ "$TRAVIS_BRANCH" == "master" ]; then DEPLOY="example-elixir"; else DEPLOY="example-elixir-staging"; fi
- echo $DEPLOY
- kubectl set image deployment/$DEPLOY example-phoenix-app=firestarter/example-phoenix-app:$VERSION

